# Generated by Django 5.2.11 on 2026-07-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated feature tags, e.g. "6-in-1 Combo, Longwear Makeup"', max_length=500),
        ),
    ]
